### ISSUE TITLE
Hammerdin dont use hammer

### ISSUE THREAD

**Issue by Skuz76** [bottytools/botty#771]
Hello,

All work pretty good but just one thing my hammer use teleport/aura but dont do hammer...
the spell is bind in ''Z" but my character in pindel teleport in and run in the corner...and my merc do the job.
I dont know why sometimes he do hammer or sometimes nothing and wait...:D

Anyone can help me ? Thank's

Sorry for this little english i'm french btw.

**Comment by pascalwinter** [comment]
Hammer should be bound to the left side skill. Also, make sure your stand_still key binding is set properly as well to something other than "shift"

**Comment by holgerrrr** [comment]
The same problem for me, hammer is bound on the left skill slot and stand_still: capslock. the character only uses teleport no hammer or concentration.

**Comment by pascalwinter** [comment]
Have you ran the F9 command to adjust D2R settings? It should turn off quick cast which should be off as well.

**Comment by holgerrrr** [comment]
> Have you ran the F9 command to adjust D2R settings? It should turn off quick cast which should be off as well.

Hi, yes it seems there is something wierd with the templates. "Waiting for templates Diablo_0 Diablo_2 Diablo_3 and after that: Teleport cancel detected. Try same teleport again. and it keeps repeating this pattern every game over and over.

**Comment by holgerrrr** [comment]
Diablo_CS_Entrance 0,2,3

**Comment by holgerrrr** [comment]
> Have you ran the F9 command to adjust D2R settings? It should turn off quick cast which should be off as well.

Tested on run_eldritch_shenk and it acts the same way. Very wierd but interesting!

**Comment by eskruolis** [comment]
Same issue here,  all settings are set to correctly, if i do not define teleport button it does run pindle and eldritch with no probs, but once teleport defined it just teleports right in to middle of crowd and stands. Afterwards trys to walk randomly and then errors with failed to find path.

**Comment by namdnas23** [comment]
Hmmm I run hammerdin as well. I am running it as development though and not from a compiled exe. How are you all running the application? Are you running from powershell as development or from a compiled version of this repo?

**Comment by pascalwinter** [comment]
No issues here running pre-compiled with Hammerdin. I've seen issues with the Teleport cancellation on EU realm while I'm in US. Not sure if it's a mix of lag and/or needing to adjust casting frames a bit.

**Comment by namdnas23** [comment]
> No issues here running pre-compiled with Hammerdin. I've seen issues with the Teleport cancellation on EU realm while I'm in US. Not sure if it's a mix of lag and/or needing to adjust casting frames a bit.

You have a point with casting frames. Have you checked for your FCR what casting frame you should be using? I have noticed at times though where I have lagged and moved into the corner. Maybe need to add a little more delay to the cast in place option?

**Comment by NeoIsrafil** [comment]
It does seem like something broke pretty heavily in the last little bit.  7.3 compiled version is giving me quite a lot of errors in the debug.  the hammerdin specifically is having a lot of issues.  My sorc doesn't have the same problems running shenk and such, but since she doesnt have chaos sanc pathing yet  i can't test her on chaos to determine if somehow blizzard pooched the hammerdin, or the chaos sanc path, or both, or neither.
