### ISSUE TITLE
Typos in default.nip

### ISSUE THREAD

**Issue by hutber** [bottytools/botty#904]
I would like to raise a PR for this, but I do not have permission. 

There are more, but first one is:

[Name] == Chippedaamethyst > [Name] == Chippedamethyst

**Comment by hutber** [comment]
And necromancersummoningskilltab

**Comment by D2RLegit** [comment]
It's open source anyone can make a pr for this. However you can let us know if theres more you find and we can review it.

**Comment by hutber** [comment]
Interesting, I wonder why I couldn't push:
(base) hutber@hutber:/var/www/botty$ git push --set-upstream origin fix-default.nip-typos
remote: Permission to aeon0/botty.git denied to hutber.
fatal: unable to access 'https://github.com/aeon0/botty.git/': The requested URL returned error: 403

**Comment by D2RLegit** [comment]
You have to fork and create a new branch. You cant merge directly to master.

**Comment by Antizerg** [comment]
I know necromancersummoningskilltab is causing issues anywhere it is used on the default.nip, but what is the fix?

**Comment by Ezro** [comment]
Resolving this ticket as it should be fixed in master
