### ISSUE TITLE
This line cannot work for loading bnip or nip

### ISSUE THREAD

**Issue by ruitwang** [bottytools/botty#936]
https://github.com/bottytools/botty/blob/859e8e725f5be68fa5c2f1957e126ca136704311/src/bnip/actions.py#L223

Need to modify to the below and that works for me.
bnip_file_paths = glob.glob(glob_bnip_path, recursive=True)+glob.glob(glob_nip_path, recursive=True)

**Comment by Ezro** [comment]
@ruitwang Can you please provide more detail around this? (how your local directory configured? How did you have it configured when it wasn't working?)

**Comment by ruitwang** [comment]
> @ruitwang Can you please provide more detail around this? (how your local directory configured? How did you have it configured when it wasn't working?)

With the original file, the program says it can not find any nip or bnip file in the bnip folder, the program always use the default bnip file as failback.
I thought it might be a file lookup issue so checked the source code.
After modifying this sentence,  the number of bnip or nip files can be correctly recognized by the program and work as expected.
