### ISSUE TITLE
Hammerdin Charged teleport to Diablo

### ISSUE THREAD

**Issue by PrivateName55** [bottytools/botty#945]
I´m not sure if this is an issue. I understand the config file that way that its possible to use an amulett with teleport charges for my Hammerdin. Teleport with charges is recognized but than game is aborted because telport is required to do diablo. This message is not loged in the log file.

**Comment by jobithu** [comment]
It is not intended to run diablo with Tele charges. There are more teleports than a typical amulet has charges. A revised version for diablo is in the works - also covering walking chars, traversing river of flame with 7 teleport charges .
